services:
  server:
    container_name: accounting
    build: . 
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/accounting
    environment:
      - XERO_BASE_URL=http://xero:3000
  xero:
    container_name: mock_xero
    image: jaypeng2015/show-me-the-money
    ports:
      - 4000:3000
    
