FROM golang:1.22 AS build 
ARG VERSION
WORKDIR /go/src/balancesheet

COPY go.mod go.sum ./
RUN go mod download 

ADD . .
RUN go install ./cmd/service

FROM debian:bookworm
ARG VERSION
RUN apt-get update \
    && apt-get install -y -q --no-install-recommends

COPY --from=build /go/bin/service /bin/apiserver
ENTRYPOINT [ "apiserver"]

LABEL image.authors="Manish Chaulagain" \
      image.version=${VERSION} 